FROM python

WORKDIR /app

COPY . /app

CMD ["python", "bmi.py"]

# Create image with name/tag: docker build -t python .

# Create container: docker run -it --rm --name python python:latest
# -it makes it interactive
# --rm deletes the container when it is finished